services:
  pd:
    container_name: pd
    image: pingcap/pd:latest
    command:
        - --name=pd
        - --data-dir=/data
        - --client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://pd:2379
        - --peer-urls=http://0.0.0.0:2380
        - --log-file=/dev/stderr
    restart: on-failure
    ports:
      - 2379:2379
  tikv:
    container_name: tikv
    image: pingcap/tikv:latest
    command:
        - --addr=0.0.0.0:20160
        - --advertise-addr=127.0.0.1:20160
        - --pd=pd:2379
        - --data-dir=/data
        - --log-file=/dev/stderr
    restart: on-failure
    ports:
      - 20160:20160
