// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Mutation struct {
}

type NewTodo struct {
	Text   string    `json:"text"`
	UserID uuid.UUID `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID          uuid.UUID `json:"id"`
	Text        string    `json:"text"`
	Done        bool      `json:"done"`
	User        *User     `json:"user"`
	SomeCasing  bool      `json:"Some_casing"`
	OtherCasing bool      `json:"otherCasing"`
}

type User struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Todos []*Todo   `json:"todos,omitempty"`
}
